version: "3"
services:
    discoveryserver:
        container_name: discoveryserver
        build: ./discoveryserver
        image: vatsal09/discoveryserver
        ports:
            - "8761:8761"
        restart: always
    apigateway:
        container_name: apigateway
        build: ./apigateway
        image: vatsal09/apigateway
        restart: always
        ports:
            - "9999:9999"
        depends_on:
            - "discoveryserver"
        links:
            - discoveryserver:discoveryserver
        environment:
            - discoveryserver_url=http://discoveryserver:8761/eureka
    booking:
        container_name: booking
        build: ./booking
        image: vatsal09/booking
        restart: always
        ports:
            - "9094:9094"
        depends_on:
            - "discoveryserver"
        links:
            - discoveryserver:discoveryserver
        environment:
            - discoveryserver_url=http://discoveryserver:8761/eureka
    customer:
        container_name: customer
        build: ./customer
        image: vatsal09/customer
        restart: always
        ports:
            - "9091:9091"
        depends_on:
            - "discoveryserver"
        links:
            - discoveryserver:discoveryserver
        environment:
            - discoveryserver_url=http://discoveryserver:8761/eureka
    service:
        container_name: service
        build: ./service
        image: vatsal09/service
        restart: always
        ports:
            - "8089:8089"
        depends_on:
            - "discoveryserver"
        links:
            - discoveryserver:discoveryserver
        environment:
            - discoveryserver_url=http://discoveryserver:8761/eureka
    worker:
        container_name: worker
        build: ./worker
        image: vatsal09/worker
        restart: always
        ports:
            - "9099:9099"
        depends_on:
            - "discoveryserver"
        links:
            - discoveryserver:discoveryserver
        environment:
            - discoveryserver_url=http://discoveryserver:8761/eureka
    payment:
        container_name: payment
        build: ./payment
        image: vatsal09/payment
        restart: always
        ports:
            - "9096:9096"
        depends_on:
            - "discoveryserver"
        links:
            - discoveryserver:discoveryserver
        environment:
            - discoveryserver_url=http://discoveryserver:8761/eureka
    notification:
        container_name: notification
        build: ./notification
        image: vatsal09/notification
        restart: always
        ports:
            - "9191:9191"
        depends_on:
            - "discoveryserver"
        links:
            - discoveryserver:discoveryserver
        environment:
            - discoveryserver_url=http://discoveryserver:8761/eureka
    activemq:
        container_name: activemq
        image: rmohr/activemq
        ports:
            - "61616:61616"
            - "8161:8161"
    jaeger-allinone:
        image: jaegertracing/all-in-one:1.7
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 14268:14268
            - 9411:9411